<template>
    <v-app id="tube">
        <h1>Terms and Conditions</h1>
        <p>Welcome to Tube. Tube is a collection of services, including the Tube website, application, and technology platform (collectively the “Tube Platform”) operated by the Corporation for Digital Scholarship (“CDS”) from its offices within the United States on a not-for-profit basis. Your access to and use of the Tube Platform are subject to these Terms of Service (“Terms of Service”) and all applicable laws. CDS makes no representation that the Tube Platform is appropriate or available for use in other locations, and access to them from territories where such access is illegal is prohibited. CDS may change or modify these Terms of Service, in whole or in part, at any time by updating this posting, without prior notice or liability to users. By accessing and/or using the Tube Platform, you acknowledge that you have read, understood and agree to be bound by these Terms of Service and to comply with all applicable laws. The terms “you”, “your” or “user”, as used in these Terms of Service, refer to a Visitor or a Registered User.</p>
        <h2>The Tube Platform</h2>
        <p>The Tube platform provides a marketplace where persons who seek documents/scans (“Clients”) can be matched with persons situated in or near to the repository where the documents being sought are located (“Agents”). Clients and Agents are collectively referred to herein as “Users,” and each User shall create a User account that enables access to the Tube Platform. Each person may only create one User account, and Tube reserves the right to shut down any additional accounts. As a User, you authorize Tube to match you with a Client or Agent based on factors such as your location, the location of the document or documents being sought, user preferences, and platform efficiency, and to cancel an existing match and rematch based on the same considerations. For purposes of these Terms of Service, the provision of documents/scans by Agents for Clients that are matched through the Tube Platform shall be referred to collectively as the “Services”. Any decision by a User to offer or accept Services is a decision made in such User’s sole discretion. Each document/scan provision Service provided by an Agent to a Client shall constitute a separate agreement between such persons.</p>
        <ol>
        	<li>
        		<h3>Your Account/Registration</h3>
        		<p>Registration is required to use the Services. The Tube Platform may only be used by individuals who can form legally binding contracts under applicable law. The Tube Platform is not available to children (persons under the age of 18) or Users who have had their User account temporarily or permanently deactivated. By becoming a User, you represent and warrant to CDS that: (a) you are 18 years of age or older and the age of majority in your state of residence as of the time you register as a Registered User; (b) all information provided by you to CDS during the registration process is truthful, accurate and complete; (c) you will comply with all terms and conditions of these Terms of Service; and (d) you will not use the Services for any purpose that is unlawful or prohibited by these Terms of Services. You may not allow other persons to use your User account, and you agree that you are the sole authorized user of your account. By registering, you also represent and warrant to CDS that: As a Registered User, you agree to maintain and promptly update your registration data as necessary to keep it accurate, current and complete. CDS may terminate your access to the Services, without prior notice or liability to you, if any of the information provided is found to be inaccurate, false, out of date or incomplete, or for violating these Terms of Service and/or the law.
				</p>
				<p>As a Registered User, you acknowledge that you are solely responsible for all activities that occur under your account while using the Services. You agree to abide by all applicable laws in connection with your use of the Services, including those related to intellectual property rights, data privacy, international communications and the transmission of technical or personal data.</p>
				<p>You are responsible for maintaining the security of your account as well as monitoring and controlling access to your account. You agree to notify CDS immediately of any unauthorized use of any account, or any other known or suspected breach of security. CDS cannot and will not be liable for any loss or damage in the event of an unauthorized use by a third party of your account. CDS, in its sole discretion, has the right to suspend or terminate your account and refuse any and all current or future use of the Services, or any other service, for any reason at any time. Termination of the Services will result in the deactivation or deletion of your account or your access to your account, and the forfeiture and relinquishment of all content in your account. If CDS terminates your account or services without cause, it will issue a pro-rata refund of any unused Services. CDS reserves the right to refuse service to anyone for any reason at any time.
				</p>
        	</li>
        	<li>
        		<h3>Tube Communications</h3>
        		<p>By entering into this Agreement or using the Platform, you agree to receive communications from us, including via e-mail, text message, calls, and push notifications. You agree that texts, calls or prerecorded messages may be generated by automatic telephone dialing systems. Communications from Tube and its affiliated companies may include but are not limited to: operational communications concerning your User account or use of the Tube Platform or Services, updates concerning new and existing features on the Tube Platform, communications concerning promotions run by us or our third-party partners, and news concerning Tube and industry developments. Standard text messaging charges applied by your cell phone carrier will apply to text messages we send.</p>
        	</li>
        	<li>
        		<h3>Your Submissions and Other Data</h3>
        		<p>CDS does not claim ownership of any data or other content you transmit, upload or store on or through the Tube Platform by any means (“Submissions”). You are solely responsible for all your Submissions and all activity that occurs under your account. You have sole responsibility for the accuracy, quality, integrity, legality, reliability, appropriateness, and intellectual property ownership or right to transmit or upload your Submissions and to grant the rights granted by you herein. CDS is not responsible for screening or monitoring data transmitted, uploaded or stored through the Services by you or other users. If notified of any data transmitted, posted or uploaded through the Services allegedly in violation of these Terms of Service, CDS may investigate the allegation and determine in good faith and its sole discretion whether to remove such data or any portion thereof. CDS shall have no liability or responsibility to users for performance or nonperformance of such activities.</p>
        	</li>
        </ol>
        <h2>Charges</h2>
        <p>As a Client, you understand that request or use of the Services may result in charges to you (“Charges”). Charges include applicable fees, surcharges, and taxes. Tube has the authority and reserves the right to determine pricing at the time you make a request. Pricing may vary based on the type of service you request, including such factors as number of pages, location of document, availability of agents, time of day, and other factors to be determined by Tube. You shall be responsible for all Charges incurred under your User account regardless of your awareness of such Charges or the amounts thereof.</p>
        <ol>
        	<li>
        		<h3>Cancellation Fee</h3>
        		<p>After requesting a document you may cancel it through the app, but note that in certain cases a cancellation fee may apply.</p>
        	</li>
        	<li>
        		<h3>Facilitation of Charges</h3>
        		<p>All Charges are facilitated through a third-party payment processing service (e.g., Stripe, Inc., or Braintree, a division of PayPal, Inc.). Tube may replace its third-party payment processing services without notice to you. Charges shall only be made through the Tube Platform. Cash payments are strictly prohibited. Your payment of Charges to Tube satisfies your payment obligation for your use of the Tube Platform and Services.</p>
        	</li>
        	<li>
        		<h3>No Refunds</h3>
        		<p>All Charges are non-refundable. This no-refund policy shall apply at all times regardless of your decision to terminate usage of the Tube Platform, any disruption to the Tube Platform or Services, or any other reason whatsoever.</p>
        	</li>
        	<li>
        		<h3>Coupons</h3>
        		<p>You may receive coupons that you can apply toward payment of certain Charges upon completion of a job. Coupons are only valid for use on the Tube Platform, and are not transferable or redeemable for cash except as required by law. Coupons cannot be combined, and if the cost of your ride exceeds the applicable credit or discount value we will charge your payment method on file for the outstanding cost of the job. For quoted or variable charges,Tube may deduct the amount attributable to the Service Fee, or Other Charges before application of the coupon. Additional restrictions on coupons may apply as communicated to you in a relevant promotion.</p>
        	</li>
        	<li>
        		<h3>Credit Card Authorization</h3>
        		<p>Upon addition of a new payment method, Tube may seek authorization of your selected payment method to verify the payment method, ensure the cost of the job will be covered, and protect against unauthorized behavior. The authorization is not a charge, however, it may reduce your available credit by the authorization amount until your bank’s next processing cycle. Should the amount of our authorization exceed the total funds on deposit in your account, you may be subject to overdraft of NSF charges by the bank issuing your debit or prepaid card. We cannot be held responsible for these charges and are unable to assist you in recovering them from your issuing bank.</p>
        	</li>
        </ol>
        <h2>Payments</h2>
        <p>As an Agent you are entitled to a payment for each job you fulfill (the “Agent Payment”). The payment consists of a base amounts plus incremental amounts based on several variables, including the number of pages included in the request. The amount of the Agent Payment will be displayed to you before you agree to fulfill a request. In situations where a client cancels a request in violation of Tube’s cancellation policy, we may charge the client a cancellation fee on your behalf. In those cases, your payment will be the amount of the cancellation penalty minus a service fee. </p>
        <p>Tube reserves the right to adjust or withhold all or a portion of a payment owed to you if (i) it believes that you have attempted to defraud or abuse clients, Tube or Tube’s payment systems, or (ii) in order to resolve a client complaint (e.g., you failed to deliver services). Tube’s decision to adjust or withhold payment in any way shall be exercised in a reasonable manner. We will use reasonable efforts to ensure that payments to you will be paid to you on at least a weekly basis. You acknowledge and agree that all payments owed to you shall not include any interest and will be net of any amounts that we are required to withhold by law.
		</p>
		<p>For each Tube request, Tube will charge the Client an amount calculated or determined by Tube on your behalf (the “Client Charges”). Unless we indicate to you otherwise, for each request, the Client Charges include the “Agent Payment,” fees retained by us, and any Third Party Fees. “Third Party Fees” include any applicable financial processing fees, or any state or local fees, surcharges or taxes imposed on the provision of Services that Tube is required by law or agreement to collect and remit to third parties.</p>
		<ol>
			<li>
				<h3>Payment Processing</h3>
				<p>Payment processing services are provided by Stripe and subject to the <a href="https://stripe.com/us/connect-account/legal">Stripe Connected Account Agreement</a>, which includes the <a href="https://stripe.com/us/legal">Stripe Services Agreement</a> (collectively, the "Stripe Terms"). By using the Tube Platform to receive payment proceeds, you agree to be bound by the Stripe Terms, which may be modified from time to time. As a condition of Tube enabling payment processing services through Stripe, you authorize Tube to obtain all necessary access and perform all necessary activity on your Stripe Connected Account to facilitate your provision of Services as contemplated by the Agreement and your relationship with Tube. You further agree to provide accurate and complete information about you and your business, and authorize Tube to share it and transaction information with Stripe for the purposes of facilitating of the payment processing services provided by Stripe. Tube reserves the right to switch payment processing vendors in its discretion.</p>
			</li>
			<li>
				<h3>Promotions and Coupons</h3>
				<p>Tube may, at its discretion, offer promotional or other Coupons to Clients, however such discounts shall not impact the Agent Payment or any other payments owed to you. You agree that Tube may sell passes or subscriptions (each, a “Tube Pass”) on your behalf to generate additional leads for your Services. Tube Passes entitle Clients to receive discounted or capped price for qualifying requests (subject to certain limitations, terms and conditions). When a Client uses a Tube Pass to place a qualifying request, Tube will use the Tube Pass payment in satisfaction of the ride total Charges subject to the terms and conditions of the Tube Pass. Your payment for Services arranged with a Tube Pass will be determined based on the Agent Payment for the ride as provided herein. In the event that Tube Pass collections from a Client exceed qualifying Charges (if any), you agree that as between you and Tube, and to the extent permitted by law, Tube may retain such excess amounts in consideration for Tube’s sales and marketing of Tube Passes.</p>
			</li>
			<li>
				<h3>No Additional Amounts</h3>
				<p>You acknowledge and agree that, for the mutual benefit of the parties, through advertising and marketing, Tube and its Affiliates may seek to generate additional demand for your Services from new and existing Clients. You acknowledge and agree such advertising or marketing does not entitle you to any additional monetary amounts beyond the amounts expressly set forth in this Agreement. As an Agent on the Tube Platform, you acknowledge and agree that you and Tube are in a direct business relationship, and the relationship between the parties under this Agreement is solely that of independent contracting parties. You and Tube expressly agree that (1) this is not an employment agreement and does not create an employment relationship between you and Tube; and (2) no joint venture, franchisor- franchisee, partnership, or agency relationship is intended or created by this Agreement. You have no authority to bind Tube, and you undertake not to hold yourself out as an employee, agent or authorized representative of Tube.
				</p>
				<p>Tube does not, and shall not be deemed to, direct or control you generally or in your performance under this Agreement specifically, including in connection with your provision of Services or your acts or omissions. You retain the sole right to determine when, where, and for how long you will utilize the Tube Platform. You retain the option to accept or to decline or ignore a Client’s request for Services via the Tube Platform, or to cancel an accepted request for Services via the Tube Platform, subject to Tube’s then-current cancellation policies. With the exception of any signage required by law or permit/license rules or requirements, Tube shall have no right to require you to: (a) wear a uniform; or (b) display Tube’s names, logos or colors. You acknowledge and agree that you have complete discretion to provide Services or otherwise engage in other business or employment activities.</p>
			</li>
		</ol>
		<h2>Acceptable Use and Conduct/User Restrictions</h2>
		<p>As a condition of your access and use of the Services, you agree that you will use the Services in compliance with these Terms of Service and all applicable laws, including any laws regarding the transmission of technical data exported from your country of residence and all export controls and embargo restrictions under the laws of the United States.</p>
		<p>You further agree that you shall not: (a) impersonate any individual or entity or misrepresent your affiliation with any other individual or entity; (b) use the Services in any manner with the intent to interrupt, damage, disable, overburden or impair the Services; (c) use the Services in violation of CDS' or any third party's intellectual property or other proprietary or legal rights; (d) use the Services in violation of any applicable laws and/or to encourage illegal activities; (e) attempt (or encourage or support anyone else's attempt) to circumvent, reverse engineer, decrypt or otherwise alter or interfere with the Services or make any unauthorized use thereof; (f) access, tamper with, or use non-public areas of the Services, CDS’ computer systems, or the technical delivery systems of CDS’ providers or otherwise obtain or attempt to obtain any content, materials or information through any means not intentionally made publicly available or provided for through the Services; (g) probe, scan, or test the vulnerability of any system or network or breach or circumvent any security or authentication measures or otherwise attempt to gain unauthorized access to the Services through hacking, password mining or any other means; (h) use or attempt to use any “spider”, “robot”, “bot”, “scraper”, “data miner” or any other program, device or algorithm, process or methodology to access, acquire, copy, or monitor the Services (or portions thereof); (i) forge any TCP/IP packet header or any part of the header information in any email or posting, or in any way use the Services to send altered, deceptive or false source-identifying information; (j) interfere with, or disrupt, (or attempt to do so), the access of any user, host or network, including, without limitation, sending a virus, overloading, flooding, spamming, mail-bombing the Services, or by taking any action that would interfere with or create an undue burden on the Services; or (k) use the Services in any way that might bring CDS into disrepute.
		</p>
		<p>Any commercial or promotional distribution, publishing or exploitation of the Services is strictly prohibited unless you have received the express prior written permission from authorized personnel of CDS, CDS’ licensors or the otherwise applicable rights holders.</p>
		<h2>Intellectual Property</h2>
		<p>All intellectual property rights in the Tube Platform shall be owned by absolutely and in their entirety by CDS and/or its partners, including the University of Connecticut. These rights include database rights, copyright, design rights (whether registered or unregistered), trademarks (whether registered or unregistered) and other similar rights wherever existing in the world together with the right to apply for protection of the same. All other trademarks, logos, service marks, company or product names set forth in the Tube Platform are the property of their respective owners. You acknowledge and agree that any questions, comments, suggestions, ideas, feedback or other information (“Submissions”) provided by you to us are non-confidential and shall become the sole property of Tube. Tube shall own exclusive rights, including all intellectual property rights, and shall be entitled to the unrestricted use and dissemination of these Submissions for any purpose, commercial or otherwise, without acknowledgment or compensation to you.</p>
		<p>Tube and other Tube logos, designs, graphics, icons, scripts and service names are registered trademarks, trademarks or trade dress of Tube in the United States and/or other countries (collectively, the “Tube Marks”). If you provide Services as an Agent, Tube grants to you, during the term of this Agreement, and subject to your compliance with the terms and conditions of this Agreement, a limited, revocable, non-exclusive license to display and use the Tube Marks solely in connection with providing the Services through the Tube Platform (“License”). The License is non-transferable and non-assignable, and you shall not grant to any third party any right, permission, license or sublicense with respect to any of the rights granted hereunder without Tube’s prior written permission, which it may withhold in its sole discretion. The Tube Marks may not be used in any manner that is likely to cause confusion.</p>
		<p>You acknowledge that Tube is the owner and licensor of the Tube Marks, including all goodwill associated therewith, and that your use of the Tube Marks will confer no additional interest in or ownership of the Tube Marks in you but rather inures to the benefit of Tube. You agree to use the Tube Marks strictly in accordance with Tube’s Trademark Usage Guidelines, as may be provided to you and revised from time to time, and to immediately cease any use that Tube determines to nonconforming or otherwise unacceptable.</p>
		<p>You agree that you will not: (1) create any materials that use the Tube Marks or any derivatives of the Tube Marks as a trademark, service mark, trade name or trade dress, other than as expressly approved by Tube in writing; (2) use the Tube Marks in any way that tends to impair their validity as proprietary trademarks, service marks, trade names or trade dress, or use the Tube Marks other than in accordance with the terms, conditions and restrictions herein; (3) take any other action that would jeopardize or impair Tube’s rights as owner of the Tube Marks or the legality and/or enforceability of the Tube Marks, including, challenging or opposing Tube’s ownership in the Tube Marks; (4) apply for trademark registration or renewal of trademark registration of any of the Tube Marks, any derivative of the Tube Marks, any combination of the Tube Marks and any other name, or any trademark, service mark, trade name, symbol or word which is similar to the Tube Marks; (5) use the Tube Marks on or in connection with any product, service or activity that is in violation of any law, statute, government regulation or standard.
		</p>
		<p>Violation of any provision of this License may result in immediate termination of the License, in Tube’s sole discretion. If you create any materials bearing the Tube Marks (in violation of this Agreement or otherwise), you agree that upon their creation Tube exclusively owns all right, title and interest in and to such materials, including any modifications to the Tube Marks or derivative works based on the Tube Marks. You further agree to assign any interest or right you may have in such materials to Tube, and to provide information and execute any documents as reasonably requested by Tube to enable Tube to formalize such assignment.
		</p>
		<p>Tube respects the intellectual property of others, and expects Users to do the same. If you believe, in good faith, that any materials on the Tube Platform or Services infringe upon your copyrights, please view the Copyright Policy herein for information on how to make a copyright complaint.</p>
		<h2>Changes to and Termination of the Services</h2>
		<p>We aim to continually improve the delivery and content of the Services and, as a result, CDS will make changes to the Services from time to time. New features may be added, but we also may modify or discontinue (temporarily or permanently) any element of the Services, in whole or in part. We will notify you if there are any material changes to the Services either via an email to the email associated with your account or via a notice displayed in the Tube app or on the Site.
		</p>
		<p>There are some circumstances under which the Services may be terminated:</p>
		<ol>
			<li>In the event that we cannot obtain commercially-practical rates or terms from a service provider or supplier, we may cease to offer the Services. In such case, we will provide thirty-days prior notice via email to the email associated with your account or via a notice displayed in the Tube app or on the Site. </li>
			<li>We may also cease to offer the Services for any other reason, in which case we will provide you with a thirty-days prior notice via email to the email associated with your account or via a notice displayed in the Tube app or on the Site. CDS reserves the right, at any time, to disable the Services temporarily for security or maintenance reasons.</li>
		</ol>
		<br>
		<h2>Modification to the Agreement</h2>
		<p>In the event Tube modifies the terms and conditions of this Agreement, such modifications shall be binding on you only upon your acceptance of the modified Agreement. Tube reserves the right to modify any information referenced in the hyperlinks from this Agreement from time to time, and such modifications shall become effective upon posting. Continued use of the Tube Platform or Services after any such changes shall constitute your consent to such changes. </p>
		<h2>Privacy</h2>
		<p>As a non-profit enterprise intended to support the development and use of open source scholarship and cultural collaboration, CDS takes privacy very seriously. In order for you to access certain areas and functions/features of the Site and register with CDS (become a Registered User), we may ask you to establish certain login information and provide us with information that personally identifies you, such as your name and email address (“Personal Information”). If you communicate with us by email or otherwise complete online forms or the like, any information provided in such communication may be collected as Personal Information. The information collection and use policies of CDS with respect to the privacy of such Personal Information are set forth in the Site's Privacy Policy, which is located at [   ] and incorporated herein by reference.</p>
		<h2>Copyright</h2>
		<p>You may access third-party content in your use of the Services. You may not remove any third party's copyright notices or other identifier, except as allowed by the third-party's license of that content. CDS is not responsible for any content provided by any third party.</p>
		<p>All Submissions and other data and content made available through the Services must comply with U.S. copyright law. Pursuant to the Digital Millennium Copyright Act (17 U.S.C. §512, as amended), if you believe in good faith that copyrighted work has been copied, adapted, reproduced through use of the Services in a manner that constitutes copyright infringement, you may submit written notification of the claimed infringing activity to our Designated Agent, Alex H. Pyle, Sheehan Phinney Bass + Green PA, 255 State Street, 5th Floor, Boston, MA 02109. To be effective, the notification of claimed infringement must include the following information:
		</p>
		<ol type="A">
			<li>A physical or electronic signature of a person authorized to act on behalf of the owner of the exclusive right that is allegedly infringed;</li>
			<li>Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site;</li>
			<li>Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information sufficient to permit CDS to locate the material;</li>
			<li>Information reasonably sufficient to permit CDS to contact the complaining party, such as an address, telephone number and, if available, an electronic mail address at which the complaining party may be contacted;</li>
			<li>A statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</li>
			<li>A statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of the exclusive right that is allegedly infringed.</li>
		</ol>
		<br>
		<p>Please consult your legal advisor before submitting written notification, as the above-stated requirements may have changed. For further information about the DMCA, please visit the website of the U.S. Copyright Office at: <a href="http://www.copyright.gov/onlinesp/">http://www.copyright.gov/onlinesp/</a>.</p>
		<p>In appropriate circumstances, CDS, at its sole discretion, may suspend or terminate any user’s access to the Services and/or take other action against users where infringing activity is apparent, regardless of whether the material or activity is ultimately determined to be infringing.</p>
		<h2>Limitation of Liability</h2>
		<p>To the maximum extent permitted by applicable law, CDS and its service providers, suppliers and licensors, and their respective directors, shareholders, officers, employees and agents will not be liable for any direct, indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the services; (ii) any conduct or content of any third party on the site or through use of the services, including without limitation, any defamatory, offensive or illegal conduct of other users or third parties; (iii) any content obtained from or through the services; and (iv) unauthorized access, use or alteration of your submissions or other content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not CDS has been informed of the possibility of such damage.</p>
		<h2>Disclaimer of Warranties</h2>
		<p>Your access to and use of the site and the services or any content is at your own risk. You understand and agree that the site and the services are provided to you on an “as is” basis without any warranties of any kind, either express or implied. Without limiting the foregoing, to the fullest extent permitted by law, CDS and its service providers, suppliers and licensors, and their respective directors, shareholders, officers, employees and agents, hereby disclaim all express, implied, statutory and other warranties, guarantees or representations, including, without limitation, any warranties of title, merchantability, non-infringement of third parties’ rights, or fitness for particular purpose or need. </p>
		<p>We make no warranty and disclaim all responsibility and liability for the completeness, accuracy, availability, timeliness, security or reliability of the services or any content thereon. CDS will not be responsible or liable for any harm to your computer system, loss of data, or other harm that results from your access to or use of the services, or any content made available through the services. You also agree that CDS has no responsibility or liability for the deletion of, or the failure to store or to transmit, any content and other communications maintained by the services. You should ensure that you have suitable backups of all of your data. We make no warranty that the services will meet your requirements or be available on an uninterrupted, secure, or error-free basis. No advice or information, whether oral or written, obtained from CDS or through the services, will create any warranty not expressly made herein.</p>
		<p>The Tube platform is provided on an “as is” basis and without any warranty or condition, express, implied or statutory. We do not guarantee and do not promise any specific results from use of the Tube platform and/or the services, including the ability to provide or receive services at any given location or time. We cannot ensure that a client or agent will complete an arranged request. We have no control over the quality of work that occurs as a result of the services. To the fullest extent permitted by law, we specifically disclaim any implied warranties of title, merchantability, fitness for a particular purpose and non-infringement. Some states do not allow the disclaimer of implied warranties, so the foregoing disclaimer may not apply to you.</p>
		<p>We do not warrant that your use of the Tube platform or services will be accurate, complete, reliable, current, secure, uninterrupted, always available, or error-free, or will meet your requirements, that any defects in the Tube platform will be corrected, or that the Tube platform is free of viruses or other harmful components. We disclaim liability for, and no warranty is made with respect to, connectivity and availability of the tube platform or services.</p>
		<p>We cannot guarantee that each user is who he or she claims to be. Please use common sense when using the Tube platform and services. Please note that there are also risks of dealing with underage persons or people acting under false pretense, and we do not accept responsibility or liability for any content, communication or other use or access of the Tube platform by persons under the age of 18 in violation of this agreement. </p>
		<p>Tube is not responsible for the conduct, whether online or offline, of any user of the Tube platform or services. You are solely responsible for your interactions with other users. By using the Tube platform and participating in the services, you agree to accept such risks and agree that Tube is not responsible for the acts or omissions of users on the Tube platform or participating in the services.</p>
		<p>You are responsible for the use of your user account and Tube expressly disclaims any liability arising from the unauthorized use of your user account. Should you suspect that any unauthorized party may be using your user account or you suspect any other breach of security, you agree to notify us immediately. </p>
		<p>It is possible for others to obtain information about you that you provide, publish or post to or through the Tube platform (including any profile information you provide), send to other users, or share during the services, and to use such information to harass or harm you. We are not responsible for the use of any personal information that you disclose to other users on the Tube platform or through the services. Please carefully select the type of information that you post on the Tube platform or through the services or release to others. We disclaim all liability, regardless of the form of action, for the acts or omissions of other users (including unauthorized users, or “hackers”).</p>
		<p>Opinions, advice, statements, offers, or other information or content concerning Tube or made available through the tube platform, but not directly by us, are those of their respective authors, and should not necessarily be relied upon. Such authors are solely responsible for such content. Under no circumstances will we be responsible for any loss or damage resulting from your reliance on information or other content posted by third parties, whether on the tube platform or otherwise. We reserve the right, but we have no obligation, to monitor the materials posted on the tube platform and remove any such material that in our sole opinion violates, or is alleged to violate, the law or this agreement or which might be offensive, illegal, or that might violate the rights, harm, or threaten the safety of users or others.</p>
		<p>Location data provided by the Tube platform is for basic location purposes only and is not intended to be relied upon in situations where precise location information is needed or where erroneous, inaccurate or incomplete location data may lead to death, personal injury, property or environmental damage. Neither Tube, nor any of its content providers, guarantees the availability, accuracy, completeness, reliability, or timeliness of location data tracked or displayed by the Tube platform. Any of your information, including geolocational data, you upload, provide, or post on the Tube platform may be accessible to Tube and certain users of the Tube platform.</p>
		<p>Tube advises you to use the Tube platform with a data plan with unlimited or very high data usage limits, and Tube shall not responsible or liable for any fees, costs, or overage charges associated with any data plan you use to access the Tube platform.</p>
		<h2>Indemnity</h2>
		<p>You agree to defend, indemnify, and hold harmless CDS, its directors, shareholders, officers, employees, agents, licensors and service providers from and against any claims, factions or demands, including, without limitation, reasonable legal and accounting fees, arising out of or resulting from your use of the Services, your Submissions, your breach of these Terms of Service and/or violation of any applicable laws. We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which even you will cooperate with us in asserting any available defense.</p>
		<h2>Links</h2>
		<p>The Site may contain links to third-party websites or resources. These links are provided solely as a convenience to you. You acknowledge and agree that we are not responsible or liable for: (i) the availability or accuracy of such websites or resources; or (ii) the content, products, or services on or available from such websites or resources. Links to such websites or resources do not imply any endorsement by CDS of such websites or resources or the content, products, or services available from such websites or resources. Nor do links to such websites and resources imply that CDS is affiliated or associated with the linked-third-party site. You acknowledge sole responsibility for and assume all risk arising from your use of any such websites or resources.</p>
		<h2>Local Laws and Export Control</h2>
		<p>CDS, through the Site, provides services and uses software and technology that may be subject to United States export controls administered by the U.S. Department of Commerce, the United States Department of Treasury Office of Foreign Assets Control and other U.S. agencies. You acknowledge and agree that the Site shall not be used, and none of the underlying information, software or technology may be transferred or otherwise exported or re-exported to countries as to which the United States maintains an embargo (collectively, “Embargoed Countries”), or to or by a national or resident thereof, or any person or entity on the U.S. Department of Treasury's List of Specially Designated Nationals or the U.S. Department of Commerce's Table of Denial Orders (collectively, “Designated Nationals”). The lists of Embargoed Countries and Designated Nationals are subject to change without notice. By using the Services, you represent and warrant that you are not located in, under the control of, or a national or resident of an Embargoed Country or Designated National. You agree to comply strictly with all United States export laws and assume sole responsibility for obtaining licenses to export or re-export as may be required.</p>
		<p>CDS and its licensors make no representation that the Services are appropriate or available for use in other locations outside the United States. If you use the Services from outside the United States, you are solely responsible for compliance with all applicable laws, including without limitation export and import regulations and intellectual property laws of other countries. Any diversion of the Services and/or any content obtained from or through the Services contrary to United States laws is prohibited.</p>
		<h2>Controlling Law and Jurisdiction</h2>
		<p>These Terms of Service and any action related thereto will be governed by the laws of Virginia without regard to or application of its conflict of law provisions or your state or country of residence. All claims, legal proceedings or litigation arising in connection with the Services will be brought solely in Virginia, and you consent to the jurisdiction of and venue in such courts and waive any objection as to inconvenient forum. If you are accepting these Terms of Service on behalf of a United States federal government entity that is legally unable to accept the controlling law, jurisdiction or venue clauses above, then those clauses do not apply to you but instead these Terms of Service and any action related thereto will be will be governed by the laws of the United States of America (without reference to conflict of laws) and, in the absence of federal law and to the extent permitted under federal law, the laws of Virginia (excluding choice of law).</p>
		<h2>General</h2>
		<p>CDS makes no claims that the materials provided on or accessed through the Site are appropriate or may be downloaded outside of the United States. Access to the Site or Services may not be legal by certain persons or in certain countries. If you access the Site or Services from outside of the United States you do so at your own risk and are responsible for compliance with all applicable laws. If any provision contained herein is found to be invalid by any court having competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions set forth herein, which shall remain in full force and effect. No waiver of any term hereunder of these Terms of Service shall be deemed a further or continuing waiver of such term or any other term. These Terms of Service constitute the entire agreement between you and CDS with respect to the use of the Site. Any changes to these Terms of Service must be made in writing, signed by an authorized representative of CDS to be binding on CDS. Notwithstanding the foregoing, CDS, at its sole discretion and without notice, may change, modify, add or remove any portion of these Terms of Service, in whole or in part, at any time. Changes in these Terms of Service will be effective when posted. If the changes, in our sole discretion, are material, we will notify you via an email to the email associated with your account or via a notice displayed in the software or on the Site. Your continued use of the Site and/or the Services made available on or accessed through the Site after any changes to these Terms of Service are posted will be considered acceptance of those changes. </p>
		<p>Except as otherwise provided in these Terms of Service, all notices should be sent by registered mail to the Corporation for Digital Scholarship, 300 Boone Blvd., Suite 500, Vienna, Virginia 22182.</p>
		<p>Effective Date: February 2019</p>
        <br>
        <v-btn to="/account/settings"><span>Back</span></v-btn>
    </v-app>
</template>

<script>
    export default {}
</script>

<style scoped>
</style>