<template>
  <v-layout>
    <v-flex xs12 sm8 xl6 offset-sm2 offset-xl3>
      <h1>Terms of Use</h1>

      <h2>These Terms of Use are effective December 4, 2019, and replace any prior Terms of Use.</h2>

      <p>Welcome to Sourcery. Sourcery is a collection of services, including the Sourcery website, mobile applications, and technology platform (collectively, the "Sourcery Platform") operated by the Corporation for Digital Scholarship ("CDS", "we", "us", and "our") from its offices within the United States on a not-for-profit basis. Your access to and use of the Sourcery Platform are subject to these Terms of Use ("Terms of Use") and all applicable laws. These Terms of Use are also sometimes referred to as the "Agreement" between you and CDS. CDS makes no representation that the Sourcery Platform is appropriate or available for use in locations outside the United States, and access to them from territories where such access is illegal is prohibited. By accessing, browsing and/or using the Sourcery Platform, or by clicking an "I ACCEPT" icon, putting a checkmark in a checkbox, or providing some other means of indicating acceptance of these Terms of Use as specified by CDS, and whether you are a visitor (which means you simply browse the Sourcery Platform) or a User (which means that you have registered with CDS, as further described below), you acknowledge that you have read, understood and agree to be bound by these Terms of Use and to comply with all applicable laws. CDS may change or modify these Terms of Use, in whole or in part, at any time by updating this posting, without prior notice or liability to users, as more particularly set forth in Section 7 below. Continued use of the Sourcery Platform after any such changes shall constitute your consent to such changes. The terms "you", "your" or "user", as used in these Terms of Use, refer to a visitor or a User, as applicable. PLEASE READ THESE TERMS OF USE CAREFULLY, AS THEY CONSITUTE A LEGAL AGREEMENT BETWEEN YOU AND CDS.</p>
      <h2>1. The Sourcery Platform</h2>
      <h3>1.1    Nature of the Sourcery Platform.</h3>
      <p>The Sourcery platform provides a marketplace where persons who seek access to documents stored remotely in libraries, courthouses, town halls, and other archives ("Clients") can be matched with persons situated in or near to the repository where the documents being sought are located ("Sourcerers") who are willing to make and provide digital scans of such documents ("Research Material"). Clients and Sourcerers are collectively referred to herein as "Users," and each User shall create a User account that enables access to the Sourcery Platform. Each person may only create one User account, and CDS reserves the right to terminate any additional accounts. As a User, you authorize CDS to match you with a Client or Sourcerer based on factors such as your location, the location of the document or documents being sought, user preferences, and platform efficiency, and to cancel an existing match and rematch based on the same considerations. For purposes of these Terms of Use, the provision of Research Material by Sourcerers for Clients that are matched through the Sourcery Platform shall be referred to collectively as the "Services". Any decision by a User to offer or accept Services is a decision made in such User’s sole discretion. Each exchange of Research Material provided by a Sourcerer to a Client (referred to herein as a "Job") shall constitute a separate agreement between such persons.</p>

      <p>CDS does not provide the Services or any other document retrieval services as part of the Sourcery Platform. CDS is a neutral venue for use by Clients and Sourcerers and CDS makes no representations or warranties about the quality of Services provided by Sourcerers. Sourcerers are not under the direction or control of CDS, and Sourcerers determine, in their own discretion, whether, how, where, and when to provide Services.</p>
      <h3>1.2 Your Account/Registration.</h3>
      <p>Registration is required to use the Sourcery Platform. The Sourcery Platform may only be used by individuals who can form legally binding contracts under applicable law. The Sourcery Platform is not available to children (persons under the age of 18) or Users who have had their User account temporarily or permanently deactivated. By becoming a User, you represent and warrant to CDS that: (a) you are 18 years of age or older and the age of majority in your place of residence as of the time you register as a User; (b) all information provided by you to CDS during the registration process is truthful, accurate and complete; (c) you will comply with all terms and conditions of these Terms of Use; (d) you will not use the Services for any purpose that is unlawful or prohibited by these Terms of Use;  and (e) you will abide by all applicable laws in connection with your use of the Sourcery Platform and the Services, including those related to United States copyright and other intellectual property rights, data privacy, international communications and the transmission of technical or personal data. You may not allow other persons to use your User account, and you agree that you are the sole authorized user of your account.</p>

      <p>By registering as a User, you agree to maintain and promptly update your registration data as necessary to keep it accurate, current and complete. CDS may terminate your access to the Sourcery Platform and Services (or portions thereof), without prior notice or liability to you, if any of the information provided is found to be inaccurate, false, out of date or incomplete, or for violating these Terms of Use and/or the law.</p>

      <p>As part of the registration process, you are required to select and use a password. As a User, you acknowledge that you are solely responsible for all activities that occur under your password or account while using the Sourcery Platform and the Services. You are responsible for maintaining the security of your password as well as monitoring and controlling access to your account. You agree to notify CDS immediately of any unauthorized use of any account, or any other known or suspected breach of security. CDS cannot and will not be liable for any loss or damage in the event of an unauthorized use by a third party of your account. CDS, in its sole discretion, has the right to suspend or terminate your account and refuse any and all current or future use of the Sourcery Platform or the Services, or any other service, for any reason at any time. Termination of the Services will result in the deactivation or deletion of your account or your access to your account, and the forfeiture and relinquishment of all content in your account.</p>

      <p>If you are a User, you may deactivate your account at any time by contacting us at <span v-html="email()" />.  Once your account is deactivated, it will not be viewable on the Sourcery Platform and you will no longer be able to request or deliver Services.  Even if a User deactivates his or her account, some information previously posted or otherwise uploaded may still be accessible by third parties. CDS is not responsible for the continued accessibility of the information posted or uploaded by a User prior to the deactivation of his or her account.  You may re-activate your account by contacting us at <span v-html="email()" />.</p>

      <h3>1.3 CDS Communications; Text and Mobile.</h3>
      <p>By registering as a User, you agree to receive communications from us, including via e-mail, SMS, text message, push notifications and other electronic means, even if your phone number is on the do-not-call list. You agree that texts may be generated by automatic telephone dialing systems. Communications from CDS may include but are not limited to: operational communications concerning your User account or use of the Sourcery Platform or Services, updates concerning new and existing features on the Sourcery Platform, communications concerning promotions run by us, and news concerning Sourcery and industry developments. Standard text messaging charges applied by your cell phone carrier will apply to text messages we send. You are not required to provide this consent to receive marketing messages as a condition of purchasing any Services or using the Sourcery Platform, and you may opt out of receiving these messages at any time as described in our Privacy Policy (although you may continue to receive messages while CDS processes your request).</p>
      <h3>1.4 Your Submissions and Other Data.</h3>
      <p>CDS does not claim ownership of any Research Material, data or other content you transmit, upload or store on or through the Sourcery Platform by any means (collectively, "Submissions"). You are solely responsible for all your Submissions and all activity that occurs under your account. You have sole responsibility for the accuracy, quality, integrity, legality, reliability, appropriateness, and intellectual property ownership or right to transmit or upload your Submissions and to grant the rights granted by you herein. CDS is not responsible for screening or monitoring data transmitted, uploaded or stored through the Services by you or other Users. If notified of any data transmitted, posted or uploaded through the Services allegedly in violation of these Terms of Use, and subject to the copyright policy included herein, CDS may investigate the allegation and determine in good faith and its sole discretion whether to remove such data or any portion thereof. CDS shall have no liability or responsibility to users for performance or nonperformance of such activities.</p>

      <p>CDS DOES NOT CONDONE NOR PERMIT UNAUTHORIZED COPYING OR DISTRIBUTION OF COPYRIGHTED WORKS ON THE SOURCERY PLATFORM. YOU SHALL BE SOLELY RESPONSIBLE FOR ENSURING THAT ANY RESEARCH MATERIAL IS OBTAINED AND PREPARED IN COMPLIANCE WITH ALL APPLICABLE COPYRIGHT LAWS AND THE POLICIES OF THE REPOSITORY IN WHICH THE SOURCE DOCUMENTS ARE HOUSED.</p>

      <h3>1.5    Ratings.</h3>
      <p>CDS may provide you with the opportunity to publicly rate the performance of Users using a numerical, star-based, or similar rating system. By providing a rating, you automatically grant CDS an unrestricted, irrevocable, worldwide, royalty-free license to use, reproduce, display, publicly perform, transmit and distribute any such submitted rating, alone or as part of other works in any form, media, or technology whether now known or hereafter developed. CDS reserves the right to screen, edit or remove these ratings from the Sourcery Platform at any time.</p>
      <h2>2. Client Charges</h2>
      <p>As a Client, you understand that request for or use of the Services may result in charges to you ("Charges"). Charges include a base fee and applicable surcharges for each Job. CDS has the authority and reserves the right to determine pricing at the time you make a request. Pricing may vary based on the type of service you request, including such factors as the number of pages, location of document, availability of Sourcerers, time of day, date of the document, and other factors to be determined by CDS. You shall be responsible for all Charges incurred under your User account regardless of your awareness of such Charges or the amounts thereof. The Sourcerer, not CDS, is responsible for performing the Services.</p>
      <h3>2.1. Cancellation Fee.</h3>
      <p>After requesting Research Material you may cancel your Job through the Sourcery Platform, but note that in certain cases a cancellation fee may apply for cancelled Jobs which have been posted and already accepted by Sourcerers.</p>
      <h3>2.2. Facilitation of Charges.</h3>
      <p>All Charges are facilitated through a third-party payment processing service. CDS may replace its third-party payment processing services without notice to you. Charges shall only be made through the Sourcery Platform. Your payment of Charges to CDS satisfies your payment obligation for your use of the Sourcery Platform and Services.</p>

      <p>Payment processing services are currently provided by Stripe and subject to the Stripe Connected Account Agreement (available at https://stripe.com/us/connect-account/legal), which includes the Stripe Services Agreement (available at https://stripe.com/us/legal) (collectively, the "Stripe Terms"). By using the Sourcery Platform to make payments, you agree to be bound by the Stripe Terms, which may be modified from time to time. As a condition of CDS enabling payment processing services through Stripe, you authorize Sourcery to obtain all necessary access and perform all necessary activity on your Stripe connected account to facilitate your provision of Services as contemplated by these Terms of Use and your relationship with CDS. You further agree to provide accurate and complete information about you and your business, and authorize CDS to share it and transaction information with Stripe for the purposes of facilitating of the payment processing services provided by Stripe. CDS reserves the right to switch payment processing vendors in its discretion.</p>

      <h3>2.3. No Refunds.</h3>
      <p>All Charges are non-refundable. This no-refund policy shall apply at all times regardless of your decision to terminate usage of the Sourcery Platform, any disruption to the Sourcery Platform or Services, or any other reason whatsoever.</p>
      <h3>2.4. Coupons.</h3>
      <p>You may receive coupons ("Coupons") that you can apply, as a Client, toward payment of certain Charges upon completion of a Job. Coupons are only valid for use on the Sourcery Platform, and are not transferable or redeemable for cash except as required by law. Coupons cannot be combined, and if the cost of your Job exceeds the applicable credit or discount value we will charge your payment method on file for the outstanding cost of the Job. Additional restrictions on coupons may apply as communicated to you in a relevant promotion.</p>
      <h2>3. Sourcerer Payments</h2>
      <p>The purchase of Services is a transaction between the Client and Sourcerer. CDS’s role is to facilitate the transaction.  As a Sourcerer you are entitled to a payment for each Job you fulfill (the "Sourcerer Payment") for Clients. The payment consists of a base amount plus additional incremental amounts based on several variables, including the number of pages included in the request. The amount of the Sourcerer Payment will be displayed to you before you agree to fulfill a Client’s Job request. In situations where a Client cancels a request in violation of CDS’s cancellation policy, we may charge the Client a cancellation fee on your behalf. In those cases, your payment will be the amount of the cancellation fee minus a service fee.</p>

      <p>CDS reserves the right to adjust or withhold all or a portion of a payment owed to you if (i) it believes that you have attempted to defraud or abuse Clients, CDS or CDS’s payment systems, or (ii) in order to resolve a Client complaint (e.g., you failed to deliver Services). CDS’s decision to adjust or withhold payment in any way shall be exercised in a reasonable manner. We will use reasonable efforts to ensure that payments to you will be paid to you on at least a weekly basis, subject to the policies of our third-party payment processor. You acknowledge and agree that all payments owed to you shall not include any interest and will be net of any amounts that we are required to withhold by law.</p>

      <p>For each Job request that you fulfill, CDS will charge the Client an amount calculated or determined by CDS on your behalf. Unless we indicate to you otherwise, for each request, this amount includes the Sourcerer Payment, fees retained by us, and any Third Party Fees. "Third Party Fees," if any, include any applicable financial processing fees, or any state or local fees, surcharges or taxes imposed on the provision of Services that CDS is required by law or agreement to collect and remit to third parties.</p>

      <h3>3.1 Payment Processing.</h3>
      <p>Payment processing services are currently provided by Stripe and subject to the Stripe Terms (as defined in Section 2.2). By using the Sourcery Platform to receive payment proceeds, you agree to be bound by the Stripe Terms, which may be modified from time to time. As a condition of CDS enabling payment processing services through Stripe, you authorize Sourcery to obtain all necessary access and perform all necessary activity on your Stripe connected account to facilitate your provision of Services as contemplated by these Terms of Use and your relationship with CDS. You further agree to provide accurate and complete information about you and your business, and authorize CDS to share it and transaction information with Stripe for the purposes of facilitating of the payment processing services provided by Stripe. CDS reserves the right to switch payment processing vendors in its discretion.</p>
      <h3>3.2 Promotions and Coupons.</h3>

      <p>CDS may, at its discretion, offer promotional or other Coupons to Clients, however such discounts shall not impact the Sourcerer Payment or any other payments owed to you as a Sourcerer.</p>
      <h3>3.3. No Additional Amounts.</h3>
      <p>You acknowledge and agree that, for the mutual benefit of the parties, through advertising and marketing, CDS may seek to generate additional demand for your Services from new and existing Clients. You acknowledge and agree such advertising or marketing does not entitle you to any additional monetary amounts beyond the amounts expressly set forth in this Agreement.</p>

      <h3>3.4 Relationship with CDS.</h3>
      <p>As a User of the Sourcery Platform, whether as a Client or a Sourcerer, you acknowledge and agree that the relationship between the parties hereunder is solely that of independent contracting parties. You and CDS expressly agree that (1) this is not an employment agreement and does not create an employment relationship between you and CDS; and (2) no joint venture, franchisor- franchisee, partnership, or agency relationship is intended or created by these Terms of Use. You have no authority to bind CDS, and you undertake not to hold yourself out as an employee, agent or authorized representative of CDS.</p>

      <p>CDS does not, and shall not be deemed to, direct or control you generally or in your performance under these Terms of Use specifically, including in connection with your provision of Services or your acts or omissions. You retain the sole right to determine when, where, and for how long you will utilize the Sourcery Platform. As a Sourcerer, you retain the option to accept or to decline or ignore a Client’s request for Services via the Sourcery Platform, or to cancel an accepted request for Services via the Sourcery Platform, subject to CDS’s then-current cancellation policies.  You acknowledge and agree that you have complete discretion to provide Services or otherwise engage in other business or employment activities.</p>

      <h2>4. Acceptable Use and Conduct/User Restrictions</h2>
      <p>As a condition of your access and use of the Services, you agree that you will use the Services in compliance with these Terms of Use and all applicable laws, including any laws regarding the transmission of technical data exported from your country of residence and all export controls and embargo restrictions under the laws of the United States.</p>

      <p>You further agree that you shall not: (a) impersonate any individual or entity or misrepresent your affiliation with any other individual or entity; (b) use the Sourcery Platform in any manner with the intent to interrupt, damage, disable, overburden or impair the Sourcery Platform or the Services; (c) use the Sourcery Platform in violation of CDS's or any third party's intellectual property or other proprietary or legal rights; (d) use the Sourcery Platform in violation of any applicable laws and/or to encourage illegal activities; (e) attempt (or encourage or support anyone else's attempt) to circumvent, reverse engineer, decrypt or otherwise alter or interfere with the Sourcery Platform or the Services or make any unauthorized use thereof; (f) access, tamper with, or use non-public areas of the Sourcery Platform, CDS’s computer systems, or the technical delivery systems of CDS’s providers or otherwise obtain or attempt to obtain any content, materials or information through any means not intentionally made publicly available or provided for through the Sourcery Platform; (g) probe, scan, or test the vulnerability of any system or network or breach or circumvent any security or authentication measures or otherwise attempt to gain unauthorized access to the Sourcery Platform through hacking, password mining or any other means; (h) use or attempt to use any "spider", "robot", "bot", "scraper", "data miner" or any other program, device or algorithm, process or methodology to access, acquire, copy, or monitor the Sourcery Platform (or portions thereof); (i) forge any TCP/IP packet header or any part of the header information in any email or posting, or in any way use the Services to send altered, deceptive or false source-identifying information; (j) interfere with, or disrupt, (or attempt to do so), the access of any user, host or network, including, without limitation, sending a virus, overloading, flooding, spamming, mail-bombing the Sourcery Platform, or by taking any action that would interfere with or create an undue burden on the Sourcery Platform; or (k) use the Sourcery Platform in any way that might bring CDS into disrepute.</p>

      <p>Any commercial or promotional distribution, publishing or exploitation of the Sourcery Platform is strictly prohibited unless you have received the express prior written permission from authorized personnel of CDS, CDS’ licensors or the otherwise applicable rights holders.</p>
      <h2>5. Intellectual Property</h2>
      <p>All intellectual property rights in the Sourcery Platform, the technology and software used to provide it, and all electronic documentation and content available through the Sourcery Platform (other than Research Materials and your Submissions) are owned by absolutely and in their entirety by CDS and/or its partners and licensors. These rights include database rights, copyright, design rights (whether registered or unregistered), trademarks (whether registered or unregistered) and other similar rights wherever existing in the world together with the right to apply for protection of the same. Sourcery and other CDS logos, designs, graphics, icons, scripts and service names are registered trademarks, trademarks or trade dress of CDS in the United States and/or other countries Except for your limited right to access and use the Sourcery Platform as set forth in these Terms of Use, nothing herein licenses or conveys any of CDS’s intellectual or proprietary rights to anyone, including you. You acknowledge and agree that CDS will have a perpetual right to use and incorporate any questions, comments, suggestions, ideas, or feedback for improvement provided by you concerning the Sourcery Platform, without any obligation or compensation.</p>

      <p>CDS respects the intellectual property of others, and expects Users to do the same. If you believe, in good faith, that any materials on the Sourcery Platform or Services infringe upon your copyrights, please view the Copyright Policy herein for information on how to make a copyright complaint.</p>

      <h2>6. Changes to Sourcery Platform and Termination.</h2>
      <p>We aim to continually improve the delivery and content of the Sourcery Platform and, as a result, CDS may make changes to the Sourcery Platform and the Services available on it from time to time. New features may be added, but we also may modify or discontinue (temporarily or permanently) any element of the Sourcery Platform or available Services, in whole or in part. We will notify you if there are any material changes to the Sourcery Platform of available Services either via an email to the email address associated with your account, or via a notice displayed on the Sourcery Platform.</p>

      <p>You understand and agree that we have no obligation to provide the Sourcery Platform in any specific location or territory, nor to continue providing it once we have begun. We may cease to offer the Sourcery Platform for any other reason, in which case we will provide you with a thirty-days prior notice via email to the email associated with your account or via a notice displayed in the Sourcery Platform. CDS reserves the right, at any time, to disable the Sourcery Platform temporarily for security or maintenance reasons.</p>

      <p>We reserve the right to immediately suspend or terminate your access to the Sourcery Platform (i) if, in our sole discretion, your conduct on the Sourcery Platform is inappropriate, unsafe, dishonest, or in breach of these terms; or (ii) if necessary, in our sole discretion, to comply with the law or to protect CDS, its Users, or the public. You may suspend or terminate your use of the Sourcery Platform at any time and for any reason. If you wish to deactivate your account, please contact CDS as described in Section 1.2.</p>

      <h2>7. Modification to the Agreement</h2>
      <p>Any changes to these Terms of Use specifically agreed to between you and CDS (and not unilateral changes to the Sourcery Platform by CDS) must be made in writing and signed by an authorized representative of CDS to be binding on CDS.  Notwithstanding the foregoing, CDS, at its sole discretion, may change, modify, add or remove any portion of the Terms of Use, in whole or in part, at any time. Each time changes are made to the Terms of Use, CDS will provide notice to Users of the same, by pop up, email or other method as determined by CDS in its sole discretion. Because CDS’s Privacy Policy is incorporated into these Terms of Use, changes to the Privacy Policy will likewise be considered changes to the Terms of Use. Changes to the Terms of Use will be effective when posted.  Your use of the Sourcery Platform or any part thereof after any changes to the Terms of Use are posted will be considered acceptance of those changes.  CDS may require additional forms of consent from Users such as by clicking an "I ACCEPT" icon, putting a checkmark in a checkbox, or providing some other means of indicating acceptance of these Terms of Use as specified by CDS.</p>

      <p>It is the obligation of Users to keep CDS apprised of any email and other address changes and CDS will not be responsible for any notices that are not received due to a User’s failure to update this information.</p>
      <h2>8.  Privacy Policy</h2>

      <p>
        As a non-profit enterprise intended to support the development and use of open source scholarship and cultural collaboration, CDS takes privacy very seriously. In order for you to access certain areas and functions/features of the Sourcery Platform and register with CDS (become a User), you may be asked to establish certain login information and provide CDS with information that personally identifies you, such as your name, email address and business and/or personal telephone numbers ("Personal Information" as defined in our Privacy Policy identified below). If you communicate with us by email or otherwise complete online forms or the like, any information provided in such communication may be collected as Personal Information. The information collection and use policies of CDS with respect to the privacy of such Personal Information, including information obtained by cookies, are set forth in the <nuxt-link to="/privacy">
          Sourcery Platform's Privacy Policy
        </nuxt-link>, incorporated herein by reference. By accessing or using the Sourcery Platform, you acknowledge that you have read and understand our Privacy Policy.
      </p>

      <h2>9. Copyright</h2>
      <p>You may access third-party content in your use of the Services, including Sourcerer provided Research Materials. You may not remove any third party's copyright notices or other identifier, except as allowed by the third-party's license of that content. CDS is not responsible for any content provided by any third party.</p>

      <p>All Submissions and other data and content made available through the Services must comply with U.S. copyright law. Pursuant to the Digital Millennium Copyright Act (17 U.S.C. §512, as amended), if you believe in good faith that copyrighted work has been copied, adapted, reproduced or exhibited on the Sourcery Platform or through use of the Services in a manner that constitutes copyright infringement, you may submit written notification of the claimed infringing activity to our Designated Copyright Takedown Agent ("DCTA"), Alexander H. Pyle, by mail at Sheehan Phinney Bass + Green PA, 28 State Street, 22nd Floor, Boston, MA 02109, or by email at apyle@sheehan.com. To be effective, the notification of claimed infringement must include the following information, or such other information as required by the Digital Millennium Copyright Act then in effect:</p>

      <p>A. A physical or electronic signature of a person authorized to act on behalf of the owner of the exclusive right that is allegedly infringed;</p>

      <p>B. Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site;</p>

      <p>C. Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information sufficient to permit CDS to locate the material;</p>

      <p>D. Information reasonably sufficient to permit CDS to contact the complaining party, such as an address, telephone number and, if available, an electronic mail address at which the complaining party may be contacted;</p>

      <p>E. A statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</p>

      <p>F. A statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of the exclusive right that is allegedly infringed.</p>

      <p>We suggest that you consult your legal advisor before submitting written notification, as the above-stated requirements may have changed. For further information about the DMCA, please visit the website of the U.S. Copyright Office at: http://www.copyright.gov/onlinesp/.</p>

      <p>In appropriate circumstances, CDS, at its sole discretion, may suspend or terminate any user’s access to the Services and/or take other action against users where infringing activity is apparent, regardless of whether the material or activity is ultimately determined to be infringing. Furthermore, CDS will, in appropriate circumstances, terminate, account access rights and/or accounts of Users who are repeat infringers of the copyrights of others.</p>

      <h2>10. Limitation of Liability</h2>
      <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, CDS AND ITS SERVICE PROVIDERS, SUPPLIERS AND LICENSORS, AND THEIR RESPECTIVE DIRECTORS, TRUSTEES, SHAREHOLDERS, MEMBERS, OFFICERS, EMPLOYEES AND AGENTS WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (i) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SOURCERY PLATFORM OR THE SERVICES; (ii) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SOURCERY PLATFORM OR THROUGH USE OF THE SERVICES, INCLUDING WITHOUT LIMITATION, ANY DEFAMATORY, OFFENSIVE OR ILLEGAL CONDUCT OF OTHER USERS OR THIRD PARTIES; (iii) ANY CONTENT OBTAINED FROM OR THROUGH THE SERVICES; AND (iv) UNAUTHORIZED ACCESS, USE OR ALTERATION OF YOUR SUBMISSIONS OR OTHER CONTENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE) OR ANY OTHER LEGAL THEORY, WHETHER OR NOT CDS HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE.</p>

      <h2>11. Disclaimer of Warranties</h2>
      <p>YOUR ACCESS TO AND USE OF THE SOURCERY PLATFORM AND THE SERVICES OR ANY CONTENT IS AT YOUR OWN RISK. CDS DOES NOT GUARANTEE AND DOES NOT PROMISE ANY SPECIFIC RESULTS FROM USE OF THE SOURCERY PLATFORM AND/OR THE SERVICES, INCLUDING THE ABILITY TO PROVIDE OR RECEIVE SERVICES AT ANY GIVEN LOCATION OR TIME. CDS CANNOT ENSURE THAT A CLIENT OR SOURCERER WILL COMPLETE AN ARRANGED JOB REQUEST. CDS HAS NO CONTROL OVER THE QUALITY OF WORK THAT OCCURS AS A RESULT OF THE SERVICES. TO THE FULLEST EXTENT PERMITTED BY LAW, CDS SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. SOME JURISDICTIONS DO NOT ALLOW THE DISCLAIMER OF IMPLIED WARRANTIES, SO THE FOREGOING DISCLAIMER MAY NOT APPLY TO YOU.</p>

      <p>CDS MAKES NO WARRANTY AND DISCLAIMS ALL RESPONSIBILITY AND LIABILITY FOR THE COMPLETENESS, ACCURACY, AVAILABILITY, TIMELINESS, SECURITY OR RELIABILITY OF THE SERVICES, SUBMISSIONS, THE SOURCERY PLATFORM OR ANY CONTENT THEREON. CDS WILL NOT BE RESPONSIBLE OR LIABLE FOR ANY HARM TO YOUR COMPUTER SYSTEM, LOSS OF DATA, OR OTHER HARM THAT RESULTS FROM YOUR ACCESS TO OR USE OF THE SOURCERY PLATFORM, OR ANY CONTENT MADE AVAILABLE THROUGH THE SOURCERY PLATFORM. YOU ALSO AGREE THAT CDS HAS NO RESPONSIBILITY OR LIABILITY FOR THE DELETION OF, OR THE FAILURE TO STORE OR TO TRANSMIT, ANY CONTENT AND OTHER COMMUNICATIONS MAINTAINED BY THE SOURCERY PLATFORM. YOU SHOULD ENSURE THAT YOU HAVE SUITABLE BACKUPS OF ALL OF YOUR DATA. WE MAKE NO WARRANTY THAT THE SOURCERY PLATFORM WILL MEET YOUR REQUIREMENTS OR BE AVAILABLE ON AN UNINTERRUPTED, SECURE, OR ERROR-FREE BASIS. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM CDS OR THROUGH THE SERVICES, WILL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN.</p>

      <p>LOCATION DATA PROVIDED BY THE SOURCERY PLATFORM IS FOR BASIC LOCATION PURPOSES ONLY AND IS NOT INTENDED TO BE RELIED UPON IN SITUATIONS WHERE PRECISE LOCATION INFORMATION IS NEEDED OR WHERE ERRONEOUS, INACCURATE OR INCOMPLETE LOCATION DATA MAY LEAD TO DEATH, PERSONAL INJURY, PROPERTY OR ENVIRONMENTAL DAMAGE. NEITHER SOURCERY, NOR ANY OF ITS CONTENT PROVIDERS, GUARANTEES THE AVAILABILITY, ACCURACY, COMPLETENESS, RELIABILITY, OR TIMELINESS OF LOCATION DATA TRACKED OR DISPLAYED BY THE SOURCERY PLATFORM. ANY OF YOUR INFORMATION, INCLUDING GEOLOCATIONAL DATA, YOU UPLOAD, PROVIDE, OR POST ON THE SOURCERY PLATFORM MAY BE ACCESSIBLE TO SOURCERY AND CERTAIN USERS OF THE SOURCERY PLATFORM.</p>

      <p>CDS ADVISES YOU TO USE THE SOURCERY PLATFORM WITH A DATA PLAN WITH UNLIMITED OR VERY HIGH DATA USAGE LIMITS, AND CDS SHALL NOT RESPONSIBLE OR LIABLE FOR ANY FEES, COSTS, OR OVERAGE CHARGES ASSOCIATED WITH ANY DATA PLAN YOU USE TO ACCESS THE SOURCERY PLATFORM.</p>

      <h2>12. Indemnity</h2>
      <p>You agree to defend, indemnify, and hold harmless CDS, its directors, trustees, shareholders, officers, employees, agents, licensors and service providers from and against any claims, actions or demands, including, without limitation, reasonable legal and accounting fees, arising out of or resulting from your use of the Sourcery Platform, your Submissions, your breach of these Terms of Use and/or violation of any applicable laws. We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which even you will cooperate with us in asserting any available defense.</p>

      <h2>13. Links</h2>
      <p>The Sourcery Platform may contain links to third-party websites or resources. These links are provided solely as a convenience to you. You acknowledge and agree that we are not responsible or liable for: (i) the availability or accuracy of such websites or resources; or (ii) the content, products, or services on or available from such websites or resources. Links to such websites or resources do not imply any endorsement by CDS of such websites or resources or the content, products, or services available from such websites or resources. Nor do links to such websites and resources imply that CDS is affiliated or associated with the linked-third-party site. You acknowledge sole responsibility for and assume all risk arising from your use of any such websites or resources.</p>
      <h2>14. Local Laws and Export Control</h2>
      <p>You agree to comply with all applicable laws in connection with access to and use of the the Sourcery Platform and the Services, and any part thereof.  Without limiting the foregoing, you agree to comply with all export and import laws and regulations of the United States and other applicable jurisdictions, and you (a) represent and warrant that you are not listed on any U.S. government list of sanctioned, prohibited, restricted, denied or debarred parties or located in (or a national of) a country that is subject to a U.S. government embargo or that has been designated by the U.S. government as a "terrorist supporting" country, (b) shall not, either directly or indirectly, access or use the Sourcery Platform or any part thereof in violation of any U.S. export embargo, prohibition or restriction, including in any embargoed or sanctioned countries/regions, by sanctioned, prohibited, restricted, denied or debarred persons, or for prohibited end-uses under United States law without authorization from the United States government, and (c) shall not submit to the Sourcery Platform or any part thereof any information that is controlled under the U.S. International Traffic in Arms Regulations.</p>

      <p>CDS and its licensors make no representation that the Sourcery Platform or the Services are appropriate or available for use in other locations outside the United States, and access to them from territories where their contents are illegal is prohibited. If you use access the Sourcery Platform from outside the United States, you do so at your own risk and are solely responsible for compliance with all applicable laws, including without limitation export and import regulations and intellectual property laws of the United States and other countries. Any diversion of the Sourcery Platform and/or any content obtained from or through the Sourcery Platform contrary to United States laws is prohibited.</p>
      <h2>15. Controlling Law and Dispute Resolution</h2>
      <p>These Terms of Use are governed by the internal substantive laws of the State of Virginia, without respect to its conflict of laws principles. All disputes arising out of or relating to the Terms of Use, including its formation, performance, or alleged or actual breach, including your use of the Sourcery Platform, will be exclusively resolved under confidential binding arbitration held in Virginia before a single arbitrator and in accordance with the rules of the American Arbitration Association. The arbitrator’s award will be binding and may be entered as a judgment in any court of competent jurisdiction. To the fullest extent permitted by applicable law, no arbitration under these terms of use will be joined to an arbitration involving any other party subject to these terms of use, whether through class arbitration proceedings or otherwise. Notwithstanding the foregoing, CDS will have the right to seek injunctive or other equitable relief in any state or federal court of appropriate subject matter jurisdiction located in the state of Virginia to enforce these Terms of Use, including to prevent infringement or other violation of its or any third party’s rights. In the event equitable relief is sought, you hereby irrevocably agree to submit to the personal jurisdiction and venue of such court and will not raise a forum non conveniens or other objection to the same. You acknowledge and agree that the provisions of this Section 18 prohibit you from engaging in any other type of dispute resolution in connection with these Terms of Use and use of the Sourcery Platform, including proceedings instituted in courts, both individual and class actions.</p>

      <h2>16. General</h2>
      <p>If any provision contained herein is found to be invalid by any court having competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions set forth herein, which shall remain in full force and effect. No waiver of any term hereunder of these Terms of Service shall be deemed a further or continuing waiver of such term or any other term. To the maximum extent possible under applicable law, this Agreement will be binding on and will inure to the benefit of the legal representatives, successors and assigns of the parties hereto. These Terms of Service constitute the entire agreement between you and CDS with respect to the use of the Sourcery Platform.</p>

      <h2>17. Notices</h2>
      <p>Except as otherwise provided in these Terms of Use, all notices should be sent by registered mail to the Corporation for Digital Scholarship, 300 Boone Blvd., Suite 500, Vienna, Virginia 22182, Attn: Sourcery.</p>
    </v-flex>
  </v-layout>
</template>

<script>
export default {
    name: 'Terms',
    data () {
        return {
            sourceryEmail: 'support@sourceryapp.org'
        }
    },
    methods: {
        email () {
            return `<a href="mailto:${this.sourceryEmail}">${this.sourceryEmail}</a>`
        }
    }
}
</script>

<style scoped>
</style>
