#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Update dependencies
echo "Installing Dependencies"
yarn


# Install or update functions
functions_directory="functions"
echo "Installing Cloud Functions in $functions_directory"
if [ -d "$functions_directory" ]
then
    cd $functions_directory && git pull
else
    git clone git@github.com:GreenhouseStudios/sourcery-functions.git $functions_directory
    cd $functions_directory
fi

echo "Installing Dependencies for the Cloud Functions"
yarn --cwd functions
