name: Deploy to Dev Firebase Hosting

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master # Only run on pushes to master

jobs:
  development:
    name: Deploy to Dev
    environment: development
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout master branch"
      uses: actions/checkout@v4
      with:
        ref: 'master'

    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - run: npm ci
    - run: npm run generate
      env:
        NODE_ENV: development
        BASE_URL: ${{ vars.BASE_URL }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        SOURCERY_ENV: ${{ vars.SOURCERY_ENV }}
        GOOGLE_ANALYTICS_ID: ${{ vars.GOOGLE_ANALYTICS_ID }}

    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SOURCERY_DEV }}'
        channelId: live
        projectId: sourcery-dev
        target: sourcery-dev
